### ISSUE TITLE
reporting error

### ISSUE THREAD

**Issue by ELKecham** [Magisk-Modules-Alt-Repo/magisk_overlayfs#3]
[magisk_install_log_2022-04-20T17_18_01.log](https://github.com/Magisk-Modules-Alt-Repo/magisk_overlayfs/files/8525224/magisk_install_log_2022-04-20T17_18_01.log)

[err_output.txt](https://github.com/Magisk-Modules-Alt-Repo/magisk_overlayfs/files/8525226/err_output.txt)

Magisk says the module is not working ☹️
Redmi note 8 pro (begonia) CrDroid 8.4 Android 12.1 (L)

**Comment by ELKecham** [comment]
1.14 works just fine

**Comment by HuskyDG** [comment]
Might fix in v1.15

**Comment by HuskyDG** [comment]
Might fix in v1.16

**Comment by ELKecham** [comment]
Fixed on 1.16 :)
