### ISSUE TITLE
Error v1.16

### ISSUE THREAD

**Issue by psychoela** [Magisk-Modules-Alt-Repo/magisk_overlayfs#4]
![Screenshot_20220421-205338_Alpha](https://user-images.githubusercontent.com/6722465/164463138-d547122f-338f-4058-b381-8c2d0be10a36.png)
After update v1.16 overlay not work anymore
[magisk_install_log_2022-04-21T20_53_45.log](https://github.com/Magisk-Modules-Alt-Repo/magisk_overlayfs/files/8531180/magisk_install_log_2022-04-21T20_53_45.log)
[err_output_v1.16.txt](https://github.com/Magisk-Modules-Alt-Repo/magisk_overlayfs/files/8531184/err_output_v1.16.txt)

**Comment by HuskyDG** [comment]
There are no specific errors in logs
Can you tell me what is not working?

**Comment by psychoela** [comment]
![Screenshot_20220425-185602_Momo](https://user-images.githubusercontent.com/6722465/165076081-dc360ff8-0206-4c17-8a75-64e2ed244690.png)
![Screenshot_20220425-185620_Alpha](https://user-images.githubusercontent.com/6722465/165076091-8d32dfe9-2fb4-4fc9-bc6f-a7066a50058e.png)

**Comment by psychoela** [comment]
This module do not hide custom rom anymore

**Comment by HuskyDG** [comment]
> This module do not hide custom rom anymore

https://github.com/Magisk-Modules-Alt-Repo/magisk_overlayfs/releases/tag/v1.17
